apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-providers
  namespace: flux-system
data:
  providers.yaml: |+
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      updateIntervalSeconds: 30
      disableDeletion: true
      editable: true
      allowUiUpdates: true
      options:
        path: /etc/grafana/dashboards
        foldersFromFilesStructure: true
